export const articles = [
  {
    id: 1,
    category: '사회',
    title: '도시의 빈 공간이 주민을 위한 작은 정원으로 바뀐다',
    summary:
      '오랫동안 방치됐던 유휴 공간을 생활권 녹지로 되살리는 시민 참여 프로젝트가 첫발을 뗐다.',
    reporter: '김하늘 기자',
    publishedAt: '2026-08-21',
    publishedLabel: '2026.08.21',
    readTime: '4분',
    accent: '#1463ff',
    visual: 'garden',
  },
  {
    id: 2,
    category: '기술',
    title: '지역 문제를 푸는 공공 데이터, 시민의 도구가 되려면',
    summary:
      '데이터의 개방을 넘어 누구나 이해하고 활용할 수 있게 만드는 새로운 실험들을 살펴봤다.',
    reporter: '이준호 기자',
    publishedAt: '2026-08-20',
    publishedLabel: '2026.08.20',
    readTime: '6분',
    accent: '#0b9a93',
    visual: 'data',
  },
  {
    id: 3,
    category: '문화',
    title: '골목의 오래된 극장, 다시 동네의 무대가 되다',
    summary:
      '문을 닫았던 소극장이 주민과 청년 예술가의 손을 거쳐 새로운 문화 거점으로 돌아왔다.',
    reporter: '박소연 기자',
    publishedAt: '2026-08-20',
    publishedLabel: '2026.08.20',
    readTime: '5분',
    accent: '#173a5c',
    visual: 'culture',
  },
  {
    id: 4,
    category: '환경',
    title: '비가 오면 달라지는 거리, 기후에 적응하는 도시 설계',
    summary:
      '빗물을 흡수하고 열기를 낮추는 거리 설계가 집중호우와 폭염의 대안으로 주목받고 있다.',
    reporter: '정유진 기자',
    publishedAt: '2026-08-19',
    publishedLabel: '2026.08.19',
    readTime: '7분',
    accent: '#328cb7',
    visual: 'climate',
  },
  {
    id: 5,
    category: '교육',
    title: '교실 밖에서 배우는 하루, 마을 전체가 배움터로',
    summary:
      '도서관과 작업실, 작은 가게까지 연결한 마을 교육 과정이 학생들의 일상을 넓히고 있다.',
    reporter: '윤서진 기자',
    publishedAt: '2026-08-18',
    publishedLabel: '2026.08.18',
    readTime: '5분',
    accent: '#55748e',
    visual: 'education',
  },
  {
    id: 6,
    category: '인터뷰',
    title: '“좋은 변화는 질문을 멈추지 않는 데서 시작합니다”',
    summary:
      '지역 혁신 현장에서 10년간 활동해 온 기획자에게 지속 가능한 변화의 조건을 물었다.',
    reporter: '최민재 기자',
    publishedAt: '2026-08-17',
    publishedLabel: '2026.08.17',
    readTime: '8분',
    accent: '#0846c9',
    visual: 'interview',
  },
]
